# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1200, 650)
        Widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.jtech = QtWidgets.QLabel(Widget)
        self.jtech.setGeometry(QtCore.QRect(0, 0, 1221, 71))
        self.jtech.setStyleSheet(
            "color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "color: rgb(0, 0, 255);\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.59901 rgba(54, 238, 241, 255));\n"
            "font: 700 italic 32pt \"Segoe UI\";")
        self.jtech.setObjectName("jtech")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(0, 70, 1201, 581))
        self.label.setStyleSheet(
            "background-color: qlineargradient(spread:reflect, x1:0.218, y1:0.188, x2:1, y2:1, stop:0.20297 rgba(222, 14, 17, 255), stop:0.752475 rgba(103, 92, 229, 255));\n"
            "color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.59901 rgba(54, 238, 241, 255));\n"
            "font: 700 italic 30pt \"Segoe UI\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.bg = QtWidgets.QLabel(Widget)
        self.bg.setGeometry(QtCore.QRect(890, 70, 311, 421))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("C:\\Users\\arunj\\PycharmProjects\\Jarvis1\\GUI files\\ironman-portrait.webp"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.bg1 = QtWidgets.QLabel(Widget)
        self.bg1.setGeometry(QtCore.QRect(0, 440, 1201, 211))
        self.bg1.setText("")
        self.bg1.setPixmap(QtGui.QPixmap("C:\\Users\\arunj\\PycharmProjects\\Jarvis1\\GUI files\\background-cropped.gif"))
        self.bg1.setScaledContents(True)
        self.bg1.setObjectName("bg1")
        self.anim = QtWidgets.QLabel(Widget)
        self.anim.setGeometry(QtCore.QRect(370, 70, 521, 371))
        self.anim.setText("")
        self.anim.setPixmap(QtGui.QPixmap("C:\\Users\\arunj\\PycharmProjects\\Jarvis1\\GUI files\\techcircle.gif"))
        self.anim.setScaledContents(True)
        self.anim.setObjectName("anim")
        self.pg = QtWidgets.QLabel(Widget)
        self.pg.setGeometry(QtCore.QRect(0, 70, 371, 181))
        self.pg.setText("")
        self.pg.setPixmap(QtGui.QPixmap("C:\\Users\\arunj\\PycharmProjects\\Jarvis1\\GUI files\\B.G_Template_1.gif"))
        self.pg.setScaledContents(True)
        self.pg.setObjectName("pg")
        self.load = QtWidgets.QLabel(Widget)
        self.load.setGeometry(QtCore.QRect(0, 250, 371, 191))
        self.load.setText("")
        self.load.setPixmap(QtGui.QPixmap("C:\\Users\\arunj\\PycharmProjects\\Jarvis1\\GUI files\\tech loading.gif"))
        self.load.setScaledContents(True)
        self.load.setObjectName("load")
        self.listen = QtWidgets.QLabel(Widget)
        self.listen.setGeometry(QtCore.QRect(0, 250, 371, 191))
        self.listen.setText("")
        self.listen.setPixmap(QtGui.QPixmap("C:\\Users\\arunj\\PycharmProjects\\Jarvis1\\GUI files\\listening.gif"))
        self.listen.setScaledContents(True)
        self.listen.setObjectName("listen")
        self.speak = QtWidgets.QLabel(Widget)
        self.speak.setGeometry(QtCore.QRect(0, 250, 371, 191))
        self.speak.setText("")
        self.speak.setPixmap(QtGui.QPixmap("C:\\Users\\arunj\\PycharmProjects\\Jarvis1\\GUI files\\speaking.gif"))
        self.speak.setScaledContents(True)
        self.speak.setObjectName("speak")
        self.sleep = QtWidgets.QLabel(Widget)
        self.sleep.setGeometry(QtCore.QRect(0, 250, 371, 191))
        self.sleep.setText("")
        self.sleep.setPixmap(QtGui.QPixmap("C:\\Users\\arunj\\PycharmProjects\\Jarvis1\\GUI files\\sleepmode.gif"))
        self.sleep.setScaledContents(True)
        self.sleep.setObjectName("sleep")

        self.exit = QtWidgets.QPushButton(Widget)
        self.exit.setGeometry(QtCore.QRect(1030, 600, 131, 41))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("QPushButton#exit{\n"
                                "    font: 700 italic 12pt \"Segoe UI\";\n"
                                "    background-color: qlineargradient(spread:reflect, x1:0.361, y1:0.267045, x2:0.831683, y2:0.756, stop:0.148515 rgba(131, 241, 243, 255), stop:0.89604 rgba(162, 112, 255, 255));\n"
                                "color:rgba(255, 255, 255, 210);\n"
                                "border-radius:20px;\n"
                                "}\n"
                                "QPushButton#exit:hover{\n"
                                "    background-color: qlineargradient(spread:pad, x1:0.144, y1:0.199, x2:0.812, y2:0.784, stop:0.0891089 rgba(249, 8, 12, 255), stop:0.777228 rgba(249, 252, 5, 255));\n"
                                "}\n"
                                "QPushButton#exit:pressed{\n"
                                " padding-left:5px;\n"
                                "padding-top:5px;\n"
                                "    background-color: rgb(150, 123, 111, 255);\n"
                                "}\n"
                                "")
        self.exit.setObjectName("exit")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.jtech.setText(_translate("Widget", "                      JARVIS TECHNOLOGY"))
        #self.Terminal.setPlaceholderText(_translate("Widget", "  ****JARVIS TERMINAL****"))
        #self.command.setPlaceholderText(_translate("Widget", "Enter Your Commands...."))
        #self.enter.setText(_translate("Widget", "ENTER"))
        self.exit.setText(_translate("Widget", "EXIT"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
